//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo
{
    using Postivo.Models.Components;
    using Postivo.Models.Errors;
    using Postivo.Utils;
    using System;

    public interface IAddressBook
    {
        public IContacts Contacts { get; }
        public IGroups Groups { get; }
    }

    public class AddressBook: IAddressBook
    {
        public SDKConfig SDKConfiguration { get; private set; }
        private const string _language = "csharp";
        private const string _sdkVersion = "0.0.36";
        private const string _sdkGenVersion = "2.723.11";
        private const string _openapiDocVersion = "1.0.1";
        public IContacts Contacts { get; private set; }
        public IGroups Groups { get; private set; }

        public AddressBook(SDKConfig config)
        {
            SDKConfiguration = config;
            Contacts = new Contacts(SDKConfiguration);
            Groups = new Groups(SDKConfiguration);
        }
    }
}