//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo
{
    using Postivo.Models.Components;
    using Postivo.Models.Errors;
    using Postivo.Utils;
    using System;

    public interface IAddressBook
    {
        public IContacts Contacts { get; }

        public IGroups Groups { get; }
    }

    public class AddressBook: IAddressBook
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// Contacts SubSDK.
        /// <see cref="IContacts"/>
        /// </summary>
        public IContacts Contacts { get; private set; }

        /// <summary>
        /// Groups SubSDK.
        /// <see cref="IGroups"/>
        /// </summary>
        public IGroups Groups { get; private set; }

        public AddressBook(SDKConfig config)
        {
            SDKConfiguration = config;
            Contacts = new Contacts(SDKConfiguration);
            Groups = new Groups(SDKConfiguration);
        }
    }
}