//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo
{
    using Newtonsoft.Json;
    using Postivo.Hooks;
    using Postivo.Models.Components;
    using Postivo.Models.Errors;
    using Postivo.Utils;
    using Postivo.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    public interface IClient
    {
        public IAccounts Accounts { get; }

        public IAddressBook AddressBook { get; }

        public IShipments Shipments { get; }

        public IMetadata Metadata { get; }

        /// <summary>
        /// Common.
        /// </summary>
        public ICommon Common { get; }

        public ISenders Senders { get; }
    }

    public class Client: IClient
    {
        /// <summary>
        /// The main SDK Configuration.
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }
        /// <summary>
        /// The Accounts sub-SDK.
        /// </summary>
        public IAccounts Accounts { get; private set; }
        /// <summary>
        /// The AddressBook sub-SDK.
        /// </summary>
        public IAddressBook AddressBook { get; private set; }
        /// <summary>
        /// The Shipments sub-SDK.
        /// </summary>
        public IShipments Shipments { get; private set; }
        /// <summary>
        /// The Metadata sub-SDK.
        /// </summary>
        public IMetadata Metadata { get; private set; }
        /// <summary>
        /// The Common sub-SDK.
        /// </summary>
        public ICommon Common { get; private set; }
        /// <summary>
        /// The Senders sub-SDK.
        /// </summary>
        public ISenders Senders { get; private set; }

        /// <summary>
        /// Initializes a new instance of the SDK based on a <see cref="SDKConfig"/> configuration object.
        /// </summary>
        /// <param name="config">The SDK configuration object.</param>
        public Client(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Accounts = new Accounts(SDKConfiguration);

            AddressBook = new AddressBook(SDKConfiguration);

            Shipments = new Shipments(SDKConfiguration);

            Metadata = new Metadata(SDKConfiguration);

            Common = new Common(SDKConfiguration);

            Senders = new Senders(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="bearer">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="bearerSource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="server">The server to use from the predefined server list.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default ClientHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        public Client(
            string? bearer = null,
            Func<string>? bearerSource = null,
            SDKConfig.Server? server = null,
            string? serverUrl = null,
            Dictionary<string, string>? urlParams = null,
            IClientHttpClient? client = null,
            RetryConfig? retryConfig = null
        )
        {

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Postivo.Models.Components.Security>? _securitySource = null;

            if(bearerSource != null)
            {
                _securitySource = () => new Postivo.Models.Components.Security() { Bearer = bearerSource() };
            }
            else if(bearer != null)
            {
                _securitySource = () => new Postivo.Models.Components.Security() { Bearer = bearer };
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ServerName = server,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Accounts = new Accounts(SDKConfiguration);

            AddressBook = new AddressBook(SDKConfiguration);

            Shipments = new Shipments(SDKConfiguration);

            Metadata = new Metadata(SDKConfiguration);

            Common = new Common(SDKConfiguration);

            Senders = new Senders(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        /// <summary>
        /// Builder class for constructing an instance of the SDK.
        /// </summary>
        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new ClientHttpClient());

            public SDKBuilder() { }

            /// <summary>
            /// Overrides the default server by name.
            /// </summary>
            public SDKBuilder WithServer(SDKConfig.Server server)
            {
                _sdkConfig.ServerName = server;
                return this;
            }

            /// <summary>
            /// Overrides the default server URL for the SDK.
            /// </summary>
            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            /// <summary>
            /// Sets the bearerSource security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithBearerSource(Func<string> bearerSource)
            {
                _sdkConfig.SecuritySource = () => new Postivo.Models.Components.Security() { Bearer = bearerSource() };
                return this;
            }

            /// <summary>
            /// Sets the bearer security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithBearer(string bearer)
            {
                _sdkConfig.SecuritySource = () => new Postivo.Models.Components.Security() { Bearer = bearer };
                return this;
            }

            /// <summary>
            /// Sets a custom HTTP client to be used by the SDK.
            /// </summary>
            public SDKBuilder WithClient(IClientHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            /// <summary>
            /// Sets the retry configuration for the SDK.
            /// </summary>
            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            /// <summary>
            /// Builds and returns the SDK instance.
            /// </summary>
            public Client Build()
            {
              return new Client(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}