//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Per-shipment callback configuration. When set, overrides the global callback defined in the user account.
    /// </summary>
    public class Callback
    {

        /// <summary>
        /// Callback target URL.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; } = default!;

        /// <summary>
        /// Bearer token to include in callback requests for authentication.
        /// </summary>
        [JsonProperty("user_token")]
        public string? UserToken { get; set; } = null;
    }
}