//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Contact details returned by the API for an Address Book entry.
    /// </summary>
    public class ContactResponse
    {

        /// <summary>
        /// Name (person or company) — line 1.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string? Name { get; set; }

        /// <summary>
        /// Name (person or company) — line 2.
        /// </summary>
        [JsonProperty("name2")]
        public string? Name2 { get; set; } = null;

        /// <summary>
        /// Street address.
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Include)]
        public string? Address { get; set; }

        /// <summary>
        /// Building number.
        /// </summary>
        [JsonProperty("home_number")]
        public string? HomeNumber { get; set; } = null;

        /// <summary>
        /// Apartment (unit) number.
        /// </summary>
        [JsonProperty("flat_number")]
        public string? FlatNumber { get; set; } = null;

        /// <summary>
        /// Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
        /// </summary>
        [JsonProperty("post_code", NullValueHandling = NullValueHandling.Include)]
        public string? PostCode { get; set; }

        /// <summary>
        /// City.
        /// </summary>
        [JsonProperty("city", NullValueHandling = NullValueHandling.Include)]
        public string? City { get; set; }

        /// <summary>
        /// Country code in ISO 3166-1 alpha-2 format. Default: &quot;PL&quot;. Value is automatically uppercased. Full list: https://www.iso.org/iso-3166-country-codes.html
        /// </summary>
        [JsonProperty("country")]
        public string? Country { get; set; } = "PL";

        /// <summary>
        /// Phone number (E.164 format recommended).
        /// </summary>
        [JsonProperty("phone_number")]
        public string? PhoneNumber { get; set; } = null;

        /// <summary>
        /// Custom (external) contact ID; must be unique per contact.
        /// </summary>
        [JsonProperty("ext_id")]
        public string? ExtId { get; set; } = null;

        /// <summary>
        /// IDs of groups the contact belongs to.
        /// </summary>
        [JsonProperty("group_ids")]
        public List<long>? GroupIds { get; set; } = null;

        /// <summary>
        /// Unique system-assigned contact ID.
        /// </summary>
        [JsonProperty("id")]
        public long Id { get; set; } = default!;
    }
}