//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// PDF document payload.
    /// </summary>
    public class DocumentPdf
    {

        /// <summary>
        /// Base64-encoded PDF content.
        /// </summary>
        [JsonProperty("file_stream")]
        public string FileStream { get; set; } = default!;

        /// <summary>
        /// Optional file name for identification purposes.
        /// </summary>
        [JsonProperty("file_name")]
        public string? FileName { get; set; } = null;
    }
}