//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Generated document content.
    /// </summary>
    public class DocumentResponse
    {

        /// <summary>
        /// Document MIME type.
        /// </summary>
        [JsonProperty("mime_type")]
        public string MimeType { get; set; } = default!;

        /// <summary>
        /// Base64-encoded document content.
        /// </summary>
        [JsonProperty("file_stream")]
        public string? FileStream { get; set; }
    }
}