//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// A document from the user&apos;s account library.
    /// </summary>
    public class DocumentLibrary
    {

        /// <summary>
        /// ID of the document stored in the user’s document library.
        /// </summary>
        [JsonProperty("id")]
        public long Id { get; set; } = default!;
    }
}