//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class DocumentsType
    {
        private DocumentsType(string value) { Value = value; }

        public string Value { get; private set; }

        public static DocumentsType DocumentPdf { get { return new DocumentsType("DocumentPdf"); } }

        public static DocumentsType DocumentLibrary { get { return new DocumentsType("DocumentLibrary"); } }

        public static DocumentsType DocumentMock { get { return new DocumentsType("DocumentMock"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(DocumentsType v) { return v.Value; }
        public static DocumentsType FromString(string v) {
            switch(v) {
                case "DocumentPdf": return DocumentPdf;
                case "DocumentLibrary": return DocumentLibrary;
                case "DocumentMock": return DocumentMock;
                default: throw new ArgumentException("Invalid value for DocumentsType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((DocumentsType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// A base document object.
    /// </summary>
    [JsonConverter(typeof(Documents.DocumentsConverter))]
    public class Documents
    {
        public Documents(DocumentsType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public DocumentPdf? DocumentPdf { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public DocumentLibrary? DocumentLibrary { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public DocumentMock? DocumentMock { get; set; }

        public DocumentsType Type { get; set; }
        public static Documents CreateDocumentPdf(DocumentPdf documentPdf)
        {
            DocumentsType typ = DocumentsType.DocumentPdf;

            Documents res = new Documents(typ);
            res.DocumentPdf = documentPdf;
            return res;
        }
        public static Documents CreateDocumentLibrary(DocumentLibrary documentLibrary)
        {
            DocumentsType typ = DocumentsType.DocumentLibrary;

            Documents res = new Documents(typ);
            res.DocumentLibrary = documentLibrary;
            return res;
        }
        public static Documents CreateDocumentMock(DocumentMock documentMock)
        {
            DocumentsType typ = DocumentsType.DocumentMock;

            Documents res = new Documents(typ);
            res.DocumentMock = documentMock;
            return res;
        }

        public class DocumentsConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Documents);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Documents(DocumentsType.DocumentLibrary)
                    {
                        DocumentLibrary = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DocumentLibrary>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DocumentLibrary), new Documents(DocumentsType.DocumentLibrary), "DocumentLibrary"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Documents(DocumentsType.DocumentMock)
                    {
                        DocumentMock = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DocumentMock>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DocumentMock), new Documents(DocumentsType.DocumentMock), "DocumentMock"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Documents(DocumentsType.DocumentPdf)
                    {
                        DocumentPdf = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<DocumentPdf>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(DocumentPdf), new Documents(DocumentsType.DocumentPdf), "DocumentPdf"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Documents res = (Documents)value;

                if (res.DocumentPdf != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DocumentPdf));
                    return;
                }

                if (res.DocumentLibrary != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DocumentLibrary));
                    return;
                }

                if (res.DocumentMock != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.DocumentMock));
                    return;
                }
            }

        }

    }
}