//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    public class Envelope
    {

        /// <summary>
        /// Unique envelope template identifier.
        /// </summary>
        [JsonProperty("envelope_id")]
        public long? EnvelopeId { get; set; }

        /// <summary>
        /// Envelope template name.
        /// </summary>
        [JsonProperty("envelope_name")]
        public string? EnvelopeName { get; set; }

        /// <summary>
        /// Maximum number of sheets supported by this envelope type.
        /// </summary>
        [JsonProperty("max_sheets")]
        public long? MaxSheets { get; set; }
    }
}