//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Problem Details object (RFC 9457) describing the error.
    /// </summary>
    public class ErrorResponse
    {

        /// <summary>
        /// URI that identifies the problem type.
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; }

        /// <summary>
        /// HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        [JsonProperty("status")]
        public long? Status { get; set; }

        /// <summary>
        /// Short, human-readable summary of the problem type.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        [JsonProperty("detail")]
        public string? Detail { get; set; }

        /// <summary>
        /// API-specific error code to help the provider team classify the error.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        /// <summary>
        /// URI that identifies this specific occurrence of the problem.
        /// </summary>
        [JsonProperty("instance")]
        public string? Instance { get; set; }
    }
}