//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Shipment configuration parameters. Overrides settings loaded from `predefined_config_id`.
    /// </summary>
    public class InlineConfig
    {

        /// <summary>
        /// Preferred carrier identifier.
        /// </summary>
        [JsonProperty("carrier_id")]
        public long CarrierId { get; set; } = default!;

        /// <summary>
        /// Preferred service identifier (shipment type).
        /// </summary>
        [JsonProperty("service_id")]
        public long ServiceId { get; set; } = default!;

        /// <summary>
        /// Preferred paper type identifier.
        /// </summary>
        [JsonProperty("paper_id")]
        public long? PaperId { get; set; }

        /// <summary>
        /// Print documents in color (`true`) or grayscale (`false`).
        /// </summary>
        [JsonProperty("color_print")]
        public bool? ColorPrint { get; set; }

        /// <summary>
        /// Print documents duplex (`true`) or single-sided (`false`).
        /// </summary>
        [JsonProperty("duplex_print")]
        public bool? DuplexPrint { get; set; }

        /// <summary>
        /// Preferred envelope size/template identifier defined in the user account.
        /// </summary>
        [JsonProperty("envelope_id")]
        public long? EnvelopeId { get; set; }

        /// <summary>
        /// Print the envelope in color (`true`) or grayscale (`false`).
        /// </summary>
        [JsonProperty("envelope_color_print")]
        public bool? EnvelopeColorPrint { get; set; }
    }
}