//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class InlineConfigUnionType
    {
        private InlineConfigUnionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static InlineConfigUnionType InlineConfig { get { return new InlineConfigUnionType("InlineConfig"); } }

        public static InlineConfigUnionType Null { get { return new InlineConfigUnionType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(InlineConfigUnionType v) { return v.Value; }
        public static InlineConfigUnionType FromString(string v) {
            switch(v) {
                case "InlineConfig": return InlineConfig;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for InlineConfigUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((InlineConfigUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(InlineConfigUnion.InlineConfigUnionConverter))]
    public class InlineConfigUnion
    {
        public InlineConfigUnion(InlineConfigUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public InlineConfig? InlineConfig { get; set; }

        public InlineConfigUnionType Type { get; set; }
        public static InlineConfigUnion CreateInlineConfig(InlineConfig inlineConfig)
        {
            InlineConfigUnionType typ = InlineConfigUnionType.InlineConfig;

            InlineConfigUnion res = new InlineConfigUnion(typ);
            res.InlineConfig = inlineConfig;
            return res;
        }

        public static InlineConfigUnion CreateNull()
        {
            InlineConfigUnionType typ = InlineConfigUnionType.Null;
            return new InlineConfigUnion(typ);
        }

        public class InlineConfigUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(InlineConfigUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new InlineConfigUnion(InlineConfigUnionType.InlineConfig)
                    {
                        InlineConfig = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<InlineConfig>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(InlineConfig), new InlineConfigUnion(InlineConfigUnionType.InlineConfig), "InlineConfig"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                InlineConfigUnion res = (InlineConfigUnion)value;
                if (InlineConfigUnionType.FromString(res.Type).Equals(InlineConfigUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.InlineConfig != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.InlineConfig));
                    return;
                }
            }

        }

    }
}