//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    public class MetadataResponseService
    {

        /// <summary>
        /// Unique service (dispatch type) identifier.
        /// </summary>
        [JsonProperty("service_id")]
        public long? ServiceId { get; set; }

        /// <summary>
        /// Service (dispatch type) name.
        /// </summary>
        [JsonProperty("service_name")]
        public string? ServiceName { get; set; }

        /// <summary>
        /// Return fee charged when the shipment is returned.
        /// </summary>
        [JsonProperty("service_return_fee")]
        public float? ServiceReturnFee { get; set; }
    }
}