//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Additional shipment metadata. At least one of `order_name` or `mpk` must be provided.
    /// </summary>
    public class MiscInfo
    {

        /// <summary>
        /// MPK (“miejsce powstania kosztu”) — billing cost-center identifier to be included on invoices.
        /// </summary>
        [JsonProperty("mpk")]
        public string? Mpk { get; set; } = null;

        /// <summary>
        /// Order name assigned to this shipment; displayed in reports and related views.
        /// </summary>
        [JsonProperty("order_name")]
        public string? OrderName { get; set; } = null;
    }
}