//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Predefined configuration usable for dispatching shipments (referenced via `predefined_config_id`).
    /// </summary>
    public class PredefinedConfig
    {

        /// <summary>
        /// Unique predefined configuration ID.
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Predefined configuration name.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Paper type name.
        /// </summary>
        [JsonProperty("paper_name")]
        public string? PaperName { get; set; }

        /// <summary>
        /// Print documents in color (`true`) or grayscale (`false`).
        /// </summary>
        [JsonProperty("color_print")]
        public bool? ColorPrint { get; set; }

        /// <summary>
        /// Print documents duplex (`true`) or single-sided (`false`).
        /// </summary>
        [JsonProperty("duplex_print")]
        public bool? DuplexPrint { get; set; }

        /// <summary>
        /// Preferred envelope type name.
        /// </summary>
        [JsonProperty("envelope_name")]
        public string? EnvelopeName { get; set; }

        /// <summary>
        /// Preferred envelope size.
        /// </summary>
        [JsonProperty("envelope_size")]
        public string? EnvelopeSize { get; set; }

        /// <summary>
        /// Envelope group name.
        /// </summary>
        [JsonProperty("envelope_group_name")]
        public string? EnvelopeGroupName { get; set; }

        /// <summary>
        /// Print the envelope in color (`true`) or grayscale (`false`).
        /// </summary>
        [JsonProperty("envelope_color_print")]
        public bool? EnvelopeColorPrint { get; set; }
    }
}