//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class Recipients2Type
    {
        private Recipients2Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static Recipients2Type RecipientInline { get { return new Recipients2Type("RecipientInline"); } }

        public static Recipients2Type RecipientFromAddressBook { get { return new Recipients2Type("RecipientFromAddressBook"); } }

        public static Recipients2Type RecipientFromAddressBookByExternalId { get { return new Recipients2Type("RecipientFromAddressBookByExternalId"); } }

        public static Recipients2Type ArrayOfRecipients1 { get { return new Recipients2Type("arrayOfRecipients1"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(Recipients2Type v) { return v.Value; }
        public static Recipients2Type FromString(string v) {
            switch(v) {
                case "RecipientInline": return RecipientInline;
                case "RecipientFromAddressBook": return RecipientFromAddressBook;
                case "RecipientFromAddressBookByExternalId": return RecipientFromAddressBookByExternalId;
                case "arrayOfRecipients1": return ArrayOfRecipients1;
                default: throw new ArgumentException("Invalid value for Recipients2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((Recipients2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
    /// </summary>
    [JsonConverter(typeof(Recipients2.Recipients2Converter))]
    public class Recipients2
    {
        public Recipients2(Recipients2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public RecipientInline? RecipientInline { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public RecipientFromAddressBook? RecipientFromAddressBook { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public RecipientFromAddressBookByExternalId? RecipientFromAddressBookByExternalId { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public List<Recipients1>? ArrayOfRecipients1 { get; set; }

        public Recipients2Type Type { get; set; }
        public static Recipients2 CreateRecipientInline(RecipientInline recipientInline)
        {
            Recipients2Type typ = Recipients2Type.RecipientInline;

            Recipients2 res = new Recipients2(typ);
            res.RecipientInline = recipientInline;
            return res;
        }
        public static Recipients2 CreateRecipientFromAddressBook(RecipientFromAddressBook recipientFromAddressBook)
        {
            Recipients2Type typ = Recipients2Type.RecipientFromAddressBook;

            Recipients2 res = new Recipients2(typ);
            res.RecipientFromAddressBook = recipientFromAddressBook;
            return res;
        }
        public static Recipients2 CreateRecipientFromAddressBookByExternalId(RecipientFromAddressBookByExternalId recipientFromAddressBookByExternalID)
        {
            Recipients2Type typ = Recipients2Type.RecipientFromAddressBookByExternalId;

            Recipients2 res = new Recipients2(typ);
            res.RecipientFromAddressBookByExternalId = recipientFromAddressBookByExternalID;
            return res;
        }
        public static Recipients2 CreateArrayOfRecipients1(List<Recipients1> arrayOfRecipients1)
        {
            Recipients2Type typ = Recipients2Type.ArrayOfRecipients1;

            Recipients2 res = new Recipients2(typ);
            res.ArrayOfRecipients1 = arrayOfRecipients1;
            return res;
        }

        public class Recipients2Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Recipients2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Recipients2(Recipients2Type.RecipientFromAddressBook)
                    {
                        RecipientFromAddressBook = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<RecipientFromAddressBook>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(RecipientFromAddressBook), new Recipients2(Recipients2Type.RecipientFromAddressBook), "RecipientFromAddressBook"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Recipients2(Recipients2Type.RecipientFromAddressBookByExternalId)
                    {
                        RecipientFromAddressBookByExternalId = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<RecipientFromAddressBookByExternalId>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(RecipientFromAddressBookByExternalId), new Recipients2(Recipients2Type.RecipientFromAddressBookByExternalId), "RecipientFromAddressBookByExternalId"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Recipients2(Recipients2Type.RecipientInline)
                    {
                        RecipientInline = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<RecipientInline>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(RecipientInline), new Recipients2(Recipients2Type.RecipientInline), "RecipientInline"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Recipients2(Recipients2Type.ArrayOfRecipients1)
                    {
                        ArrayOfRecipients1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<List<Recipients1>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(List<Recipients1>), new Recipients2(Recipients2Type.ArrayOfRecipients1), "ArrayOfRecipients1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Recipients2 res = (Recipients2)value;

                if (res.RecipientInline != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.RecipientInline));
                    return;
                }

                if (res.RecipientFromAddressBook != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.RecipientFromAddressBook));
                    return;
                }

                if (res.RecipientFromAddressBookByExternalId != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.RecipientFromAddressBookByExternalId));
                    return;
                }

                if (res.ArrayOfRecipients1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ArrayOfRecipients1));
                    return;
                }
            }

        }

    }
}