//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Select recipient data for a shipment from the Address Book.
    /// </summary>
    public class RecipientFromAddressBook
    {

        /// <summary>
        /// Global ID of the recipient stored in the personal Address Book.
        /// </summary>
        [JsonProperty("id")]
        public long Id { get; set; } = default!;

        /// <summary>
        /// User-assigned custom shipment ID.
        /// </summary>
        [JsonProperty("custom_id")]
        public string? CustomId { get; set; } = null;

        /// <summary>
        /// Optional postscript printed above the recipient data on the envelope.
        /// </summary>
        [JsonProperty("postscript")]
        public string? Postscript { get; set; } = null;
    }
}