//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Select shipment recipient data from the Address Book by external (custom) ID.
    /// </summary>
    public class RecipientFromAddressBookByExternalId
    {

        /// <summary>
        /// External (custom) ID of the recipient stored in your Address Book.
        /// </summary>
        [JsonProperty("ext_id")]
        public string ExtId { get; set; } = default!;

        /// <summary>
        /// Set to true to fetch recipient data by external ID from inherited main account’s Address Book.
        /// </summary>
        [JsonProperty("inherited")]
        public bool? Inherited { get; set; } = false;

        /// <summary>
        /// Custom shipment ID assigned by the user.
        /// </summary>
        [JsonProperty("custom_id")]
        public string? CustomId { get; set; } = null;

        /// <summary>
        /// Optional postscript printed above the recipient data on the envelope.
        /// </summary>
        [JsonProperty("postscript")]
        public string? Postscript { get; set; } = null;
    }
}