//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System;
    
    /// <summary>
    /// Additional shipment settings.
    /// </summary>
    public class RequestOptions
    {

        /// <summary>
        /// ID of the shipment configuration profile stored in the user account.
        /// </summary>
        [JsonProperty("predefined_config_id")]
        public long? PredefinedConfigId { get; set; } = null;

        [JsonProperty("inline_config", NullValueHandling = NullValueHandling.Include)]
        public InlineConfigUnion? InlineConfig { get; set; } = null;

        /// <summary>
        /// ID of the sender stored in the user account.
        /// </summary>
        [JsonProperty("sender_id")]
        public long? SenderId { get; set; } = null;

        /// <summary>
        /// Scheduled dispatch date (ISO 8601).
        /// </summary>
        [JsonProperty("dispatch_date")]
        public DateOnly? DispatchDate { get; set; }

        [JsonProperty("callback", NullValueHandling = NullValueHandling.Include)]
        public CallbackUnion? Callback { get; set; } = null;

        [JsonProperty("misc_info", NullValueHandling = NullValueHandling.Include)]
        public MiscInfoUnion? MiscInfo { get; set; } = null;

        /// <summary>
        /// If true, rotate all documents 180° before printing (barcodes will be printed on opposite margins).
        /// </summary>
        [JsonProperty("rotate_documents")]
        public bool? RotateDocuments { get; set; }
    }
}