//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    
    /// <summary>
    /// Extended sender details.
    /// </summary>
    public class SenderDetails
    {

        /// <summary>
        /// Unique sender ID.
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// Sender data for the shipment.
        /// </summary>
        [JsonProperty("sender")]
        public Sender Sender { get; set; } = default!;

        /// <summary>
        /// Indicates whether the sender is active.
        /// </summary>
        [JsonProperty("active")]
        public bool Active { get; set; } = default!;

        /// <summary>
        /// Indicates whether this is the default sender.
        /// </summary>
        [JsonProperty("default")]
        public bool Default { get; set; } = default!;
    }
}