//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Sender data for the shipment.
    /// </summary>
    public class Sender
    {

        /// <summary>
        /// Sender name (person or company) — line 1.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string? Name { get; set; }

        /// <summary>
        /// Sender name (person or company) — line 2.
        /// </summary>
        [JsonProperty("name2")]
        public string? Name2 { get; set; } = null;

        /// <summary>
        /// Street address of the sender.
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Include)]
        public string? Address { get; set; }

        /// <summary>
        /// Building number of the sender.
        /// </summary>
        [JsonProperty("home_number")]
        public string? HomeNumber { get; set; } = null;

        /// <summary>
        /// Apartment (unit) number of the sender.
        /// </summary>
        [JsonProperty("flat_number")]
        public string? FlatNumber { get; set; } = null;

        /// <summary>
        /// Postal code. For `PL`, 5-digit values are normalized to the `NN-NNN` format.
        /// </summary>
        [JsonProperty("post_code", NullValueHandling = NullValueHandling.Include)]
        public string? PostCode { get; set; }

        /// <summary>
        /// City of the sender.
        /// </summary>
        [JsonProperty("city", NullValueHandling = NullValueHandling.Include)]
        public string? City { get; set; }

        /// <summary>
        /// Country code in ISO 3166-1 alpha-2 format. Value is automatically uppercased. Full list: https://www.iso.org/iso-3166-country-codes.html
        /// </summary>
        [JsonProperty("country")]
        public string? Country { get; set; } = null;
    }
}