//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Postal operator that will handle the shipment.
    /// </summary>
    public class ShipmentPriceCarrier
    {

        /// <summary>
        /// Postal operator ID.
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; } = null;

        /// <summary>
        /// Postal operator name.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;
    }
}