//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    using System;
    
    /// <summary>
    /// Shipment processing status.
    /// </summary>
    public class ShipmentDetailsStatus
    {

        /// <summary>
        /// Indicates whether an error occurred during shipment processing.
        /// </summary>
        [JsonProperty("error")]
        public bool? Error { get; set; }

        /// <summary>
        /// Shipment status code.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }

        /// <summary>
        /// Shipment status description.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Date and time of the shipment status change (UTC).
        /// </summary>
        [JsonProperty("date")]
        public DateTime? Date { get; set; }
    }
}