//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    
    /// <summary>
    /// Properties of a new shipment.
    /// </summary>
    public class Shipment
    {

        /// <summary>
        /// Recipient data for a single shipment. For one recipient, provide a `RecipientInline`, `RecipientFromAddressBook`, or `RecipientFromAddressBookByExternalId` object. For multiple recipients, provide an array of these objects (1–50).
        /// </summary>
        [JsonProperty("recipients", NullValueHandling = NullValueHandling.Include)]
        public Recipients2 Recipients { get; set; } = default!;

        /// <summary>
        /// Document payload to print and enclose. For a single document, provide `DocumentPdf` or `DocumentLibrary`. For multiple documents, provide an array of `DocumentPdf`, `DocumentLibrary`, or `DocumentMock` objects (1–20).
        /// </summary>
        [JsonProperty("documents", NullValueHandling = NullValueHandling.Include)]
        public Documents2 Documents { get; set; } = default!;

        [JsonProperty("options", NullValueHandling = NullValueHandling.Include)]
        public Options? Options { get; set; } = null;
    }
}