//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System;
    
    /// <summary>
    /// Single shipment details
    /// </summary>
    public class ShipmentDetails
    {

        /// <summary>
        /// Unique shipment identifier.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// Custom shipment ID assigned by the user.
        /// </summary>
        [JsonProperty("custom_id")]
        public string? CustomId { get; set; } = null;

        /// <summary>
        /// Carrier-provided shipment tracking number.
        /// </summary>
        [JsonProperty("tracking_number")]
        public string? TrackingNumber { get; set; } = null;

        /// <summary>
        /// Recipient data for a shipment, including full postal address.
        /// </summary>
        [JsonProperty("recipient")]
        public Recipient? Recipient { get; set; }

        /// <summary>
        /// Sender data for the shipment.
        /// </summary>
        [JsonProperty("sender")]
        public Sender? Sender { get; set; }

        /// <summary>
        /// Shipment processing status.
        /// </summary>
        [JsonProperty("status")]
        public ShipmentDetailsStatus? Status { get; set; }

        /// <summary>
        /// Postal operator handling the shipment.
        /// </summary>
        [JsonProperty("carrier")]
        public ShipmentDetailsCarrier? Carrier { get; set; }

        /// <summary>
        /// Service (shipment type) used.
        /// </summary>
        [JsonProperty("service")]
        public ShipmentDetailsService? Service { get; set; }

        /// <summary>
        /// Dispatch date.
        /// </summary>
        [JsonProperty("dispatch_date")]
        public DateOnly? DispatchDate { get; set; } = null;

        /// <summary>
        /// Total number of pages across all documents in the shipment.
        /// </summary>
        [JsonProperty("page_number")]
        public long? PageNumber { get; set; }

        /// <summary>
        /// Shipment price (PLN).
        /// </summary>
        [JsonProperty("price")]
        public float? Price { get; set; }
    }
}