//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Components
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Details of a single shipment and its status events
    /// </summary>
    public class StatusDetails
    {

        /// <summary>
        /// Single shipment details
        /// </summary>
        [JsonProperty("shipment_details")]
        public ShipmentDetails? ShipmentDetails { get; set; }

        /// <summary>
        /// List of status events for the shipment.
        /// </summary>
        [JsonProperty("status_events")]
        public List<StatusEvent>? StatusEvents { get; set; } = null;
    }
}