//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    using System.Collections.Generic;
    
    public class CancelShipmentResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// The request was processed successfully. Check the shipment cancellation statuses in the response body.
        /// </summary>
        public List<ShipmentCancellation>? ShipmentCancellations { get; set; }

        /// <summary>
        /// Invalid request.
        /// </summary>
        public Models.Components.ErrorResponse? ErrorResponse { get; set; } = null;

        public Dictionary<string, List<string>> Headers { get; set; } = default!;
    }
}