//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Postivo.Utils;
    
    public class DeleteContactByExternalIdRequest
    {

        /// <summary>
        /// External (custom) ID of the contact to remove.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ext_id")]
        public string ExtId { get; set; } = default!;
    }
}