//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Postivo.Models.Requests;
    using Postivo.Utils;
    
    public class GetDocumentsRequest
    {

        /// <summary>
        /// Single shipment ID assigned by the system when the shipment was created.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Type of document/certificate to generate.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=type")]
        public DocumentType Type { get; set; } = default!;
    }
}