//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Postivo.Utils;
    using System.Collections.Generic;
    
    public class GetStatusRequest
    {

        /// <summary>
        /// Shipment IDs assigned by the system (comma-separated). The system accepts a maximum of **50** identifiers per call.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=true,name=ids")]
        public List<string> Ids { get; set; } = default!;
    }
}