//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Newtonsoft.Json;
    using Postivo.Models.Components;
    using Postivo.Utils;
    
    public class PingResponse
    {

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// API service is available.
        /// </summary>
        public Models.Components.PingResponse? PingResponseValue { get; set; }

        /// <summary>
        /// Invalid request.
        /// </summary>
        public Models.Components.ErrorResponse? ErrorResponse { get; set; } = null;
    }
}