//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Postivo.Models.Requests
{
    using Newtonsoft.Json;
    using Postivo.Utils;
    
    /// <summary>
    /// Verification code received in the letter.
    /// </summary>
    public class VerifySenderRequestBody
    {

        [JsonProperty("verification_code")]
        public string VerificationCode { get; set; } = default!;
    }
}