name: Build and publish nuGet package in Github Packages and NuGet Repo

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Package
      run: dotnet pack --no-restore --no-build --configuration Release  --output .

    - name: Prepare package for GitHub Packages
      run: dotnet nuget add source --username tommek83 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/postivo/index.json"

    - name: Push package to GitHub packages
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"

    - name: Push package to NuGet repo
      run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }}  --source "nuget.org"
